CREATE TABLE knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    summary TEXT,
    content TEXT NOT NULL,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_knowledge_slug UNIQUE (slug),
    CONSTRAINT ck_knowledge_visibility CHECK (visibility IN ('PRIVATE', 'UNLISTED', 'PUBLIC'))
);

CREATE INDEX idx_knowledge_owner_id ON knowledge (owner_id);
