CREATE TABLE knowledge_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) GENERATED ALWAYS AS (lower(btrim(name))) STORED,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_knowledge_collection_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT uk_knowledge_collection_owner_normalized_name UNIQUE (owner_id, normalized_name)
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID NOT NULL,
    name VARCHAR(50) NOT NULL,
    normalized_name VARCHAR(50) GENERATED ALWAYS AS (lower(btrim(ltrim(btrim(name), '#')))) STORED,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tag_name_not_blank CHECK (btrim(ltrim(btrim(name), '#')) <> ''),
    CONSTRAINT uk_tag_owner_normalized_name UNIQUE (owner_id, normalized_name)
);

ALTER TABLE knowledge
    ADD COLUMN collection_id BIGINT,
    ADD CONSTRAINT fk_knowledge_collection
        FOREIGN KEY (collection_id) REFERENCES knowledge_collection (id) ON DELETE SET NULL;

CREATE INDEX idx_knowledge_collection_id ON knowledge (collection_id);

CREATE TABLE knowledge_tag (
    knowledge_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_knowledge_tag PRIMARY KEY (knowledge_id, tag_id),
    CONSTRAINT fk_knowledge_tag_knowledge
        FOREIGN KEY (knowledge_id) REFERENCES knowledge (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_tag_tag
        FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);

CREATE INDEX idx_knowledge_tag_tag_id ON knowledge_tag (tag_id);
