CREATE TABLE knowledge_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT,
    content TEXT NOT NULL,
    collection_name VARCHAR(100),
    tags JSONB NOT NULL,
    reason VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_knowledge_revision_knowledge
        FOREIGN KEY (knowledge_id) REFERENCES knowledge (id) ON DELETE CASCADE,
    CONSTRAINT ck_knowledge_revision_reason
        CHECK (reason IN ('CREATE', 'CHECKPOINT', 'BEFORE_RESTORE')),
    CONSTRAINT ck_knowledge_revision_tags_array
        CHECK (jsonb_typeof(tags) = 'array')
);

CREATE INDEX idx_knowledge_revision_knowledge_created
    ON knowledge_revision (knowledge_id, created_at DESC, id DESC);

-- Existing notes receive a truthful migration-time checkpoint. New notes receive
-- a CREATE revision transactionally from the application service.
INSERT INTO knowledge_revision (
    knowledge_id,
    title,
    summary,
    content,
    collection_name,
    tags,
    reason,
    created_at
)
SELECT
    k.id,
    k.title,
    k.summary,
    k.content,
    c.name,
    COALESCE((
        SELECT jsonb_agg(t.name ORDER BY lower(t.name), t.name)
        FROM knowledge_tag kt
        JOIN tag t ON t.id = kt.tag_id
        WHERE kt.knowledge_id = k.id
    ), '[]'::jsonb),
    'CHECKPOINT',
    CURRENT_TIMESTAMP
FROM knowledge k
LEFT JOIN knowledge_collection c ON c.id = k.collection_id;
