CREATE EXTENSION IF NOT EXISTS vector;

-- The composite FK prevents assigning another owner's partition to a chunk.
ALTER TABLE knowledge ADD CONSTRAINT uk_knowledge_id_owner UNIQUE (id, owner_id);

CREATE TABLE knowledge_embedding_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    owner_id UUID NOT NULL,
    chunk_index INTEGER NOT NULL,
    chunk_count INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    embedding vector NOT NULL,
    embedding_model VARCHAR(255) NOT NULL,
    embedding_dimensions INTEGER NOT NULL,
    chunker_version INTEGER NOT NULL,
    source_hash VARCHAR(64) NOT NULL,
    source_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_embedding_chunk_knowledge FOREIGN KEY (knowledge_id, owner_id)
        REFERENCES knowledge (id, owner_id) ON DELETE CASCADE,
    CONSTRAINT uk_embedding_chunk_position UNIQUE (knowledge_id, chunk_index),
    CONSTRAINT ck_embedding_chunk_position CHECK (chunk_index >= 0 AND chunk_count > chunk_index),
    CONSTRAINT ck_embedding_chunk_text CHECK (btrim(chunk_text) <> ''),
    CONSTRAINT ck_embedding_chunk_model CHECK (btrim(embedding_model) <> ''),
    CONSTRAINT ck_embedding_chunk_dimensions CHECK (
        embedding_dimensions BETWEEN 1 AND 16000 AND vector_dims(embedding) = embedding_dimensions
    ),
    CONSTRAINT ck_embedding_chunk_version CHECK (chunker_version > 0),
    CONSTRAINT ck_embedding_chunk_hash CHECK (source_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_embedding_chunk_owner_model
    ON knowledge_embedding_chunk (owner_id, embedding_model, embedding_dimensions, knowledge_id);
-- Exact cosine scans for a personal library. ANN indexes are deliberately deferred.
